apiVersion: v1
kind: ConfigMap
metadata:
  name: udagram-aws
data:
  POSTGRES_HOST: postgres.c8pdnez5mtws.us-east-1.rds.amazonaws.com
  POSTGRES_DB: postgres
  AWS_BUCKET: dandevs3bucket
  credentials: |
  aws_access_key_id: ASIAZANOH4P45PWKTGUG
  aws_secret_access_key: kRZ1UssCn3gfRkMrJAz3AvRysf1EfriL/61zbn0N
  aws_session_token: FwoGZXIvYXdzEPn//////////wEaDA7xB2B7U4d9EOWNciLVAQZeKEv3SeYULBUgOLdy9HhC1ECHY2pk7kbA2RTGvdMm64rF34JekWMdCKgdI05WTOdYIqf0b4ygGF73y1skq9Jny4/1lYsMgYD8MMElG76NOQZfe4Tun4avqGQ+I5yLzzqfMiVVYdGXqdVeNFZ6DnIvM0iVZ+QTxYnC84l2RQXwzCDzSlRNwrommtMhJJQCKTFfMCw5kQB7K6J4AlW00FfwTBud3EVvCtcpjh1kng83LqmFuNb3uG9yUmmjTURCTJ2PVjHdXn2ysimZYt1JVmUwQejMjiidzaKaBjItgxrNigkRzlm4reAA41oQMuYRQPlPFBs+coDmwVnVQp56nn7In6sd3L6acxPU