apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  selector:
    matchLabels:
      app: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: dante9623/udagram-api-feed:v2
        envFrom:
          - secretRef:
              name: udagramdb-env
          - configMapRef:
              name: udagram-env
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        volumeMounts:
        - mountPath: /root/.aws/
          name: udagram-aws
        
      volumes: 
        - name: udagram-aws
          configMap: 
            name: udagram-aws