apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend
spec:
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 80
  selector:
    app: udagram-frontend
