name: monolith-to-microservices

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-frontend:local dante9623/udagram-frontend:v2
    - run: docker tag udagram-api-user dante9623/udagram-api-user:v2
    - run: docker tag udagram-api-feed dante9623/udagram-api-feed:v2
    - run: docker tag reverseproxy dante9623/udagram-reverseproxy:v2
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin
    - run: docker push dante9623/udagram-frontend:v2
    - run: docker push dante9623/udagram-api-user:v2
    - run: docker push dante9623/udagram-api-feed:v2
    - run: docker push dante9623/udagram-reverseproxy:v2
