name: monolith-to-microservices

on:
  push:
    branches:
      - 'main'
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build udagram-api-feed
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-api-feed
          push: true
          tags: dante9623/udagram-api-feed:latest, dante9623/udagram-api-feed:${{github.run_number}}
      -
        name: Build udagram-api-user
        uses: docker/build-push-action@v3
        with:  
          context: ./udagram-api-user
          push: true
          tags: dante9623/udagram-api-user:latest, dante9623/udagram-api-user:${{github.run_number}}
        
      -
        name: Build udagram-frontend
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-frontend
          push: true
          tags: dante9623/udagram-frontend:latest, dante9623/udagram-frontend:${{github.run_number}}
        
      - 
        name: Build udagram-reverseproxy
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-reverseproxy
          tags: dante9623/udagram-reverseproxy:latest, dante9623/udagram-reverseproxy:${{github.run_number}}
            
