name: monolith-to-microservices

on:
  push:
    branches:
      - 'main'
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build udagram-api-feed
        uses: docker/build-push-action@v3
        with:
          context: /monolith-to-microservices/udagram-api-feed
      -
        name: Build udagram-api-user
        uses: docker/build-push-action@v3
        with:  
          context: /monolith-to-microservices/udagram-api-user
        
      -
        name: Build udagram-frontend
        uses: docker/build-push-action@v3
        run: docker build -t udagram-frontend ./udagram-frontend
      - 
        name: Build udagram-reverseproxy
        uses: docker/build-push-action@v3
        run: docker build -t udagram-reverseproxy ./udagram-reverseproxy
        with:
          context: .
          push: true
          tags: user/app:latest
